language: python
python:
  - "3.5"
  - "3.6"
sudo: required
dist: trusty
install: pip install tox-travis codecov
script: tox
after_success:
  - tox -e coverage
  - codecov
addons:
  apt:
    packages:
      - libluabind-dev
      - libffi-dev
      - libseccomp-dev
