language: python
python:
  - "3.5"
  - "3.6"
sudo: required
dist: trusty
install: pip install setuptools==34.2.0 coverage codecov .
script: coverage run setup.py test
after_success: codecov
addons:
  apt:
    packages:
      - libluabind-dev
      - libffi-dev
      - libseccomp-dev
