language: python
python:
  - "3.6"
  - "3.7-dev"
addons:
  apt:
    packages:
      - libluabind-dev
      - libffi-dev
      - libseccomp-dev
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.7-dev"
stages:
  - lint
  - check 
  - test
install: pip install tox codecov
jobs:
  include:
    - stage: lint
      script: tox -e lint
      python: "3.6"
    - stage: check
      script: tox -e check
      python: "3.6"
script: tox -e coverage
after_success: codecov
