language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - libluabind-dev
      - libffi-dev
      - libseccomp-dev
matrix:
  fast_finish: true
stages:
  - lint
  - test
install: pip install tox codecov
jobs:
  include:
    - stage: lint
      script: tox -e lint
      python: "3.6"
script: tox -e coverage
after_success: codecov
